#############################################################################
# Makefile for building: libPlayerModules.so
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  playermodules.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile playermodules.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PLUGIN -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/taglib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PlayerModules1.0.0
DISTDIR = /home/cyrildz/Project/playermodules.repo/dev/.obj/PlayerModules1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -shared
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -ltag -lQt5Quick -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5Network -lQt5Sql -lQt5DBus -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = playermodules_plugin.cpp \
		albummodel.cpp \
		notify.cpp \
		player.cpp \
		playlist.cpp \
		playlistcontentmodel.cpp \
		tracklistmodel.cpp \
		mpris2.cpp \
		mpris2_player.cpp \
		dbusmanager.cpp \
		mpris2_Adaptor.cpp \
		mpris2_playerAdaptor.cpp \
		Notify_Adaptor.cpp \
		artistmodel.cpp \
		genremodel.cpp \
		playlistmanager.cpp \
		logger.cpp \
		queue.cpp \
		tagreaderrevisited.cpp \
		utils.cpp \
		playlistmodel.cpp \
		randomgenerator.cpp .moc/moc_playermodules_plugin.cpp \
		.moc/moc_albummodel.cpp \
		.moc/moc_notify.cpp \
		.moc/moc_player.cpp \
		.moc/moc_playlist.cpp \
		.moc/moc_playlistcontentmodel.cpp \
		.moc/moc_tracklistmodel.cpp \
		.moc/moc_mpris2.cpp \
		.moc/moc_mpris2_player.cpp \
		.moc/moc_dbusmanager.cpp \
		.moc/moc_mpris2_Adaptor.cpp \
		.moc/moc_mpris2_playerAdaptor.cpp \
		.moc/moc_Notify_Adaptor.cpp \
		.moc/moc_artistmodel.cpp \
		.moc/moc_playlistmanager.cpp \
		.moc/moc_logger.cpp \
		.moc/moc_playlistmodel.cpp
OBJECTS       = .obj/playermodules_plugin.o \
		.obj/albummodel.o \
		.obj/notify.o \
		.obj/player.o \
		.obj/playlist.o \
		.obj/playlistcontentmodel.o \
		.obj/tracklistmodel.o \
		.obj/mpris2.o \
		.obj/mpris2_player.o \
		.obj/dbusmanager.o \
		.obj/mpris2_Adaptor.o \
		.obj/mpris2_playerAdaptor.o \
		.obj/Notify_Adaptor.o \
		.obj/artistmodel.o \
		.obj/genremodel.o \
		.obj/playlistmanager.o \
		.obj/logger.o \
		.obj/queue.o \
		.obj/tagreaderrevisited.o \
		.obj/utils.o \
		.obj/playlistmodel.o \
		.obj/randomgenerator.o \
		.obj/moc_playermodules_plugin.o \
		.obj/moc_albummodel.o \
		.obj/moc_notify.o \
		.obj/moc_player.o \
		.obj/moc_playlist.o \
		.obj/moc_playlistcontentmodel.o \
		.obj/moc_tracklistmodel.o \
		.obj/moc_mpris2.o \
		.obj/moc_mpris2_player.o \
		.obj/moc_dbusmanager.o \
		.obj/moc_mpris2_Adaptor.o \
		.obj/moc_mpris2_playerAdaptor.o \
		.obj/moc_Notify_Adaptor.o \
		.obj/moc_artistmodel.o \
		.obj/moc_playlistmanager.o \
		.obj/moc_logger.o \
		.obj/moc_playlistmodel.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		playermodules.pro playermodules_plugin.h \
		albummodel.h \
		notify.h \
		player.h \
		playlist.h \
		playlistcontentmodel.h \
		tracklistmodel.h \
		mpris2.h \
		mpris2_player.h \
		dbusmanager.h \
		mpris2_Adaptor.h \
		mpris2_playerAdaptor.h \
		Notify_Adaptor.h \
		artistmodel.h \
		genremodel.h \
		playlistmanager.h \
		logger.h \
		queue.h \
		tagreader.h \
		utils.h \
		playlistmodel.h \
		randomgenerator.h \
		abstractplaylist.h playermodules_plugin.cpp \
		albummodel.cpp \
		notify.cpp \
		player.cpp \
		playlist.cpp \
		playlistcontentmodel.cpp \
		tracklistmodel.cpp \
		mpris2.cpp \
		mpris2_player.cpp \
		dbusmanager.cpp \
		mpris2_Adaptor.cpp \
		mpris2_playerAdaptor.cpp \
		Notify_Adaptor.cpp \
		artistmodel.cpp \
		genremodel.cpp \
		playlistmanager.cpp \
		logger.cpp \
		queue.cpp \
		tagreaderrevisited.cpp \
		utils.cpp \
		playlistmodel.cpp \
		randomgenerator.cpp
QMAKE_TARGET  = PlayerModules
DESTDIR       = ../../LP/lib/PlayerModules/#avoid trailing-slash linebreak
TARGET        = libPlayerModules.so
TARGETD       = libPlayerModules.so


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

../../LP/lib/PlayerModules/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../LP/lib/PlayerModules/ || mkdir -p ../../LP/lib/PlayerModules/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../LP/lib/PlayerModules/ 



Makefile: playermodules.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		playermodules.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Quick.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Qml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5DBus.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile playermodules.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
playermodules.pro:
/usr/lib/x86_64-linux-gnu/libQt5Quick.prl:
/usr/lib/x86_64-linux-gnu/libQt5Qml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5DBus.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile playermodules.pro

qmake_all: FORCE


all: Makefile ../../LP/lib/PlayerModules/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents playermodules_plugin.h albummodel.h notify.h player.h playlist.h playlistcontentmodel.h tracklistmodel.h mpris2.h mpris2_player.h dbusmanager.h mpris2_Adaptor.h mpris2_playerAdaptor.h Notify_Adaptor.h artistmodel.h genremodel.h playlistmanager.h logger.h queue.h tagreader.h utils.h playlistmodel.h randomgenerator.h abstractplaylist.h $(DISTDIR)/
	$(COPY_FILE) --parents playermodules_plugin.cpp albummodel.cpp notify.cpp player.cpp playlist.cpp playlistcontentmodel.cpp tracklistmodel.cpp mpris2.cpp mpris2_player.cpp dbusmanager.cpp mpris2_Adaptor.cpp mpris2_playerAdaptor.cpp Notify_Adaptor.cpp artistmodel.cpp genremodel.cpp playlistmanager.cpp logger.cpp queue.cpp tagreaderrevisited.cpp utils.cpp playlistmodel.cpp randomgenerator.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_playermodules_plugin.cpp .moc/moc_albummodel.cpp .moc/moc_notify.cpp .moc/moc_player.cpp .moc/moc_playlist.cpp .moc/moc_playlistcontentmodel.cpp .moc/moc_tracklistmodel.cpp .moc/moc_mpris2.cpp .moc/moc_mpris2_player.cpp .moc/moc_dbusmanager.cpp .moc/moc_mpris2_Adaptor.cpp .moc/moc_mpris2_playerAdaptor.cpp .moc/moc_Notify_Adaptor.cpp .moc/moc_artistmodel.cpp .moc/moc_playlistmanager.cpp .moc/moc_logger.cpp .moc/moc_playlistmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_playermodules_plugin.cpp .moc/moc_albummodel.cpp .moc/moc_notify.cpp .moc/moc_player.cpp .moc/moc_playlist.cpp .moc/moc_playlistcontentmodel.cpp .moc/moc_tracklistmodel.cpp .moc/moc_mpris2.cpp .moc/moc_mpris2_player.cpp .moc/moc_dbusmanager.cpp .moc/moc_mpris2_Adaptor.cpp .moc/moc_mpris2_playerAdaptor.cpp .moc/moc_Notify_Adaptor.cpp .moc/moc_artistmodel.cpp .moc/moc_playlistmanager.cpp .moc/moc_logger.cpp .moc/moc_playlistmodel.cpp
.moc/moc_playermodules_plugin.cpp: playermodules_plugin.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playermodules_plugin.h -o .moc/moc_playermodules_plugin.cpp

.moc/moc_albummodel.cpp: utils.h \
		albummodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include albummodel.h -o .moc/moc_albummodel.cpp

.moc/moc_notify.cpp: notify.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include notify.h -o .moc/moc_notify.cpp

.moc/moc_player.cpp: playlist.h \
		utils.h \
		tagreader.h \
		tracklistmodel.h \
		dbusmanager.h \
		mpris2.h \
		mpris2_player.h \
		notify.h \
		player.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include player.h -o .moc/moc_player.cpp

.moc/moc_playlist.cpp: utils.h \
		tagreader.h \
		tracklistmodel.h \
		playlist.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playlist.h -o .moc/moc_playlist.cpp

.moc/moc_playlistcontentmodel.cpp: tracklistmodel.h \
		utils.h \
		tagreader.h \
		playlistcontentmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playlistcontentmodel.h -o .moc/moc_playlistcontentmodel.cpp

.moc/moc_tracklistmodel.cpp: utils.h \
		tracklistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tracklistmodel.h -o .moc/moc_tracklistmodel.cpp

.moc/moc_mpris2.cpp: mpris2.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mpris2.h -o .moc/moc_mpris2.cpp

.moc/moc_mpris2_player.cpp: utils.h \
		tagreader.h \
		mpris2_player.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mpris2_player.h -o .moc/moc_mpris2_player.cpp

.moc/moc_dbusmanager.cpp: mpris2.h \
		mpris2_player.h \
		utils.h \
		tagreader.h \
		notify.h \
		dbusmanager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dbusmanager.h -o .moc/moc_dbusmanager.cpp

.moc/moc_mpris2_Adaptor.cpp: mpris2_Adaptor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mpris2_Adaptor.h -o .moc/moc_mpris2_Adaptor.cpp

.moc/moc_mpris2_playerAdaptor.cpp: mpris2_playerAdaptor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mpris2_playerAdaptor.h -o .moc/moc_mpris2_playerAdaptor.cpp

.moc/moc_Notify_Adaptor.cpp: Notify_Adaptor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Notify_Adaptor.h -o .moc/moc_Notify_Adaptor.cpp

.moc/moc_artistmodel.cpp: utils.h \
		artistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include artistmodel.h -o .moc/moc_artistmodel.cpp

.moc/moc_playlistmanager.cpp: playlistmanager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playlistmanager.h -o .moc/moc_playlistmanager.cpp

.moc/moc_logger.cpp: queue.h \
		utils.h \
		tagreader.h \
		logger.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include logger.h -o .moc/moc_logger.cpp

.moc/moc_playlistmodel.cpp: utils.h \
		playlistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/cyrildz/Project/playermodules.repo/dev -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playlistmodel.h -o .moc/moc_playlistmodel.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/playermodules_plugin.o: playermodules_plugin.cpp playermodules_plugin.h \
		player.h \
		playlist.h \
		utils.h \
		tagreader.h \
		tracklistmodel.h \
		dbusmanager.h \
		mpris2.h \
		mpris2_player.h \
		notify.h \
		logger.h \
		queue.h \
		albummodel.h \
		artistmodel.h \
		genremodel.h \
		playlistmodel.h \
		playlistcontentmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/playermodules_plugin.o playermodules_plugin.cpp

.obj/albummodel.o: albummodel.cpp albummodel.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/albummodel.o albummodel.cpp

.obj/notify.o: notify.cpp notify.h \
		Notify_Adaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/notify.o notify.cpp

.obj/player.o: player.cpp player.h \
		playlist.h \
		utils.h \
		tagreader.h \
		tracklistmodel.h \
		dbusmanager.h \
		mpris2.h \
		mpris2_player.h \
		notify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/player.o player.cpp

.obj/playlist.o: playlist.cpp playlist.h \
		utils.h \
		tagreader.h \
		tracklistmodel.h \
		randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/playlist.o playlist.cpp

.obj/playlistcontentmodel.o: playlistcontentmodel.cpp playlistcontentmodel.h \
		tracklistmodel.h \
		utils.h \
		tagreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/playlistcontentmodel.o playlistcontentmodel.cpp

.obj/tracklistmodel.o: tracklistmodel.cpp tracklistmodel.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tracklistmodel.o tracklistmodel.cpp

.obj/mpris2.o: mpris2.cpp mpris2.h \
		mpris2_Adaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mpris2.o mpris2.cpp

.obj/mpris2_player.o: mpris2_player.cpp mpris2_player.h \
		utils.h \
		tagreader.h \
		mpris2_playerAdaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mpris2_player.o mpris2_player.cpp

.obj/dbusmanager.o: dbusmanager.cpp dbusmanager.h \
		mpris2.h \
		mpris2_player.h \
		utils.h \
		tagreader.h \
		notify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/dbusmanager.o dbusmanager.cpp

.obj/mpris2_Adaptor.o: mpris2_Adaptor.cpp mpris2_Adaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mpris2_Adaptor.o mpris2_Adaptor.cpp

.obj/mpris2_playerAdaptor.o: mpris2_playerAdaptor.cpp mpris2_playerAdaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mpris2_playerAdaptor.o mpris2_playerAdaptor.cpp

.obj/Notify_Adaptor.o: Notify_Adaptor.cpp Notify_Adaptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Notify_Adaptor.o Notify_Adaptor.cpp

.obj/artistmodel.o: artistmodel.cpp artistmodel.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/artistmodel.o artistmodel.cpp

.obj/genremodel.o: genremodel.cpp genremodel.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/genremodel.o genremodel.cpp

.obj/playlistmanager.o: playlistmanager.cpp playlistmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/playlistmanager.o playlistmanager.cpp

.obj/logger.o: logger.cpp logger.h \
		queue.h \
		utils.h \
		tagreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/logger.o logger.cpp

.obj/queue.o: queue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/queue.o queue.cpp

.obj/tagreaderrevisited.o: tagreaderrevisited.cpp tagreader.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tagreaderrevisited.o tagreaderrevisited.cpp

.obj/utils.o: utils.cpp utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/utils.o utils.cpp

.obj/playlistmodel.o: playlistmodel.cpp playlistmodel.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/playlistmodel.o playlistmodel.cpp

.obj/randomgenerator.o: randomgenerator.cpp randomgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/randomgenerator.o randomgenerator.cpp

.obj/moc_playermodules_plugin.o: .moc/moc_playermodules_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_playermodules_plugin.o .moc/moc_playermodules_plugin.cpp

.obj/moc_albummodel.o: .moc/moc_albummodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_albummodel.o .moc/moc_albummodel.cpp

.obj/moc_notify.o: .moc/moc_notify.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_notify.o .moc/moc_notify.cpp

.obj/moc_player.o: .moc/moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_player.o .moc/moc_player.cpp

.obj/moc_playlist.o: .moc/moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_playlist.o .moc/moc_playlist.cpp

.obj/moc_playlistcontentmodel.o: .moc/moc_playlistcontentmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_playlistcontentmodel.o .moc/moc_playlistcontentmodel.cpp

.obj/moc_tracklistmodel.o: .moc/moc_tracklistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_tracklistmodel.o .moc/moc_tracklistmodel.cpp

.obj/moc_mpris2.o: .moc/moc_mpris2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mpris2.o .moc/moc_mpris2.cpp

.obj/moc_mpris2_player.o: .moc/moc_mpris2_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mpris2_player.o .moc/moc_mpris2_player.cpp

.obj/moc_dbusmanager.o: .moc/moc_dbusmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_dbusmanager.o .moc/moc_dbusmanager.cpp

.obj/moc_mpris2_Adaptor.o: .moc/moc_mpris2_Adaptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mpris2_Adaptor.o .moc/moc_mpris2_Adaptor.cpp

.obj/moc_mpris2_playerAdaptor.o: .moc/moc_mpris2_playerAdaptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mpris2_playerAdaptor.o .moc/moc_mpris2_playerAdaptor.cpp

.obj/moc_Notify_Adaptor.o: .moc/moc_Notify_Adaptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_Notify_Adaptor.o .moc/moc_Notify_Adaptor.cpp

.obj/moc_artistmodel.o: .moc/moc_artistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_artistmodel.o .moc/moc_artistmodel.cpp

.obj/moc_playlistmanager.o: .moc/moc_playlistmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_playlistmanager.o .moc/moc_playlistmanager.cpp

.obj/moc_logger.o: .moc/moc_logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_logger.o .moc/moc_logger.cpp

.obj/moc_playlistmodel.o: .moc/moc_playlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_playlistmodel.o .moc/moc_playlistmodel.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules || mkdir -p $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules
	-$(INSTALL_PROGRAM) "../../LP/lib/PlayerModules/$(TARGET)" "$(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/$(TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/ 


install_qmldir: first FORCE
	@test -d $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules || mkdir -p $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules
	-$(INSTALL_FILE) /home/cyrildz/Project/playermodules.repo/dev/qmldir $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/

uninstall_qmldir: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/qmldir
	-$(DEL_DIR) $(INSTALL_ROOT)/home/cyrildz/Project/playermodules.repo/dev/PlayerModules/ 


install:  install_target install_qmldir  FORCE

uninstall: uninstall_target uninstall_qmldir   FORCE

FORCE:

