/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a mpris2_playerAdaptor org.mpris.MediaPlayer2.Player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mpris2_playerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PlayerAdaptor
 */

PlayerAdaptor::PlayerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PlayerAdaptor::~PlayerAdaptor()
{
    // destructor
}

QString PlayerAdaptor::applicationName() const
{
    // get the value of property ApplicationName
    return qvariant_cast< QString >(parent()->property("ApplicationName"));
}

void PlayerAdaptor::setApplicationName(const QString &value)
{
    // set the value of property ApplicationName
    parent()->setProperty("ApplicationName", QVariant::fromValue(value));
}

bool PlayerAdaptor::canControl() const
{
    // get the value of property CanControl
    return qvariant_cast< bool >(parent()->property("CanControl"));
}

bool PlayerAdaptor::canGoNext() const
{
    // get the value of property CanGoNext
    return qvariant_cast< bool >(parent()->property("CanGoNext"));
}

bool PlayerAdaptor::canGoPrevious() const
{
    // get the value of property CanGoPrevious
    return qvariant_cast< bool >(parent()->property("CanGoPrevious"));
}

bool PlayerAdaptor::canPause() const
{
    // get the value of property CanPause
    return qvariant_cast< bool >(parent()->property("CanPause"));
}

bool PlayerAdaptor::canPlay() const
{
    // get the value of property CanPlay
    return qvariant_cast< bool >(parent()->property("CanPlay"));
}

bool PlayerAdaptor::canSeek() const
{
    // get the value of property CanSeek
    return qvariant_cast< bool >(parent()->property("CanSeek"));
}

QString PlayerAdaptor::loopStatus() const
{
    // get the value of property LoopStatus
    return qvariant_cast< QString >(parent()->property("LoopStatus"));
}

void PlayerAdaptor::setLoopStatus(const QString &value)
{
    // set the value of property LoopStatus
    parent()->setProperty("LoopStatus", QVariant::fromValue(value));
}

double PlayerAdaptor::maximumRate() const
{
    // get the value of property MaximumRate
    return qvariant_cast< double >(parent()->property("MaximumRate"));
}

QVariantMap PlayerAdaptor::metadata() const
{
    // get the value of property Metadata
    return qvariant_cast< QVariantMap >(parent()->property("Metadata"));
}

double PlayerAdaptor::minimumRate() const
{
    // get the value of property MinimumRate
    return qvariant_cast< double >(parent()->property("MinimumRate"));
}

QString PlayerAdaptor::playbackStatus() const
{
    // get the value of property PlaybackStatus
    return qvariant_cast< QString >(parent()->property("PlaybackStatus"));
}

qlonglong PlayerAdaptor::position() const
{
    // get the value of property Position
    return qvariant_cast< qlonglong >(parent()->property("Position"));
}

double PlayerAdaptor::rate() const
{
    // get the value of property Rate
    return qvariant_cast< double >(parent()->property("Rate"));
}

void PlayerAdaptor::setRate(double value)
{
    // set the value of property Rate
    parent()->setProperty("Rate", QVariant::fromValue(value));
}

bool PlayerAdaptor::shuffle() const
{
    // get the value of property Shuffle
    return qvariant_cast< bool >(parent()->property("Shuffle"));
}

void PlayerAdaptor::setShuffle(bool value)
{
    // set the value of property Shuffle
    parent()->setProperty("Shuffle", QVariant::fromValue(value));
}

double PlayerAdaptor::volume() const
{
    // get the value of property Volume
    return qvariant_cast< double >(parent()->property("Volume"));
}

void PlayerAdaptor::setVolume(double value)
{
    // set the value of property Volume
    parent()->setProperty("Volume", QVariant::fromValue(value));
}

QString PlayerAdaptor::ApplicationName()
{
    // handle method call org.mpris.MediaPlayer2.Player.ApplicationName
    QString out0;
    QMetaObject::invokeMethod(parent(), "ApplicationName", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool PlayerAdaptor::CanControl()
{
    // handle method call org.mpris.MediaPlayer2.Player.CanControl
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanControl", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PlayerAdaptor::CanGoNext()
{
    // handle method call org.mpris.MediaPlayer2.Player.CanGoNext
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanGoNext", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PlayerAdaptor::CanGoPrevious()
{
    // handle method call org.mpris.MediaPlayer2.Player.CanGoPrevious
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanGoPrevious", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PlayerAdaptor::CanPause()
{
    // handle method call org.mpris.MediaPlayer2.Player.CanPause
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanPause", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool PlayerAdaptor::CanPlay()
{
    // handle method call org.mpris.MediaPlayer2.Player.CanPlay
    bool out0;
    QMetaObject::invokeMethod(parent(), "CanPlay", Q_RETURN_ARG(bool, out0));
    return out0;
}

QString PlayerAdaptor::LoopStatus()
{
    // handle method call org.mpris.MediaPlayer2.Player.LoopStatus
    QString out0;
    QMetaObject::invokeMethod(parent(), "LoopStatus", Q_RETURN_ARG(QString, out0));
    return out0;
}

double PlayerAdaptor::MaximumRate()
{
    // handle method call org.mpris.MediaPlayer2.Player.MaximumRate
    double out0;
    QMetaObject::invokeMethod(parent(), "MaximumRate", Q_RETURN_ARG(double, out0));
    return out0;
}

double PlayerAdaptor::MinimumRate()
{
    // handle method call org.mpris.MediaPlayer2.Player.MinimumRate
    double out0;
    QMetaObject::invokeMethod(parent(), "MinimumRate", Q_RETURN_ARG(double, out0));
    return out0;
}

void PlayerAdaptor::Next()
{
    // handle method call org.mpris.MediaPlayer2.Player.Next
    QMetaObject::invokeMethod(parent(), "Next");
}

void PlayerAdaptor::OpenUri(const QString &uri)
{
    // handle method call org.mpris.MediaPlayer2.Player.OpenUri
    QMetaObject::invokeMethod(parent(), "OpenUri", Q_ARG(QString, uri));
}

void PlayerAdaptor::Pause()
{
    // handle method call org.mpris.MediaPlayer2.Player.Pause
    QMetaObject::invokeMethod(parent(), "Pause");
}

void PlayerAdaptor::Play()
{
    // handle method call org.mpris.MediaPlayer2.Player.Play
    QMetaObject::invokeMethod(parent(), "Play");
}

void PlayerAdaptor::PlayPause()
{
    // handle method call org.mpris.MediaPlayer2.Player.PlayPause
    QMetaObject::invokeMethod(parent(), "PlayPause");
}

QString PlayerAdaptor::PlaybackStatus()
{
    // handle method call org.mpris.MediaPlayer2.Player.PlaybackStatus
    QString out0;
    QMetaObject::invokeMethod(parent(), "PlaybackStatus", Q_RETURN_ARG(QString, out0));
    return out0;
}

void PlayerAdaptor::Previous()
{
    // handle method call org.mpris.MediaPlayer2.Player.Previous
    QMetaObject::invokeMethod(parent(), "Previous");
}

double PlayerAdaptor::Rate()
{
    // handle method call org.mpris.MediaPlayer2.Player.Rate
    double out0;
    QMetaObject::invokeMethod(parent(), "Rate", Q_RETURN_ARG(double, out0));
    return out0;
}

void PlayerAdaptor::Seek(qlonglong offset)
{
    // handle method call org.mpris.MediaPlayer2.Player.Seek
    QMetaObject::invokeMethod(parent(), "Seek", Q_ARG(qlonglong, offset));
}

void PlayerAdaptor::SetLoopStatus(const QString &Status)
{
    // handle method call org.mpris.MediaPlayer2.Player.SetLoopStatus
    QMetaObject::invokeMethod(parent(), "SetLoopStatus", Q_ARG(QString, Status));
}

void PlayerAdaptor::SetPosition(const QDBusObjectPath &trackId, qlonglong offset)
{
    // handle method call org.mpris.MediaPlayer2.Player.SetPosition
    QMetaObject::invokeMethod(parent(), "SetPosition", Q_ARG(QDBusObjectPath, trackId), Q_ARG(qlonglong, offset));
}

void PlayerAdaptor::SetRate(double rate)
{
    // handle method call org.mpris.MediaPlayer2.Player.SetRate
    QMetaObject::invokeMethod(parent(), "SetRate", Q_ARG(double, rate));
}

void PlayerAdaptor::SetShuffle(bool shuffle)
{
    // handle method call org.mpris.MediaPlayer2.Player.SetShuffle
    QMetaObject::invokeMethod(parent(), "SetShuffle", Q_ARG(bool, shuffle));
}

bool PlayerAdaptor::Shuffle()
{
    // handle method call org.mpris.MediaPlayer2.Player.Shuffle
    bool out0;
    QMetaObject::invokeMethod(parent(), "Shuffle", Q_RETURN_ARG(bool, out0));
    return out0;
}

void PlayerAdaptor::Stop()
{
    // handle method call org.mpris.MediaPlayer2.Player.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}



