Document: playermodules
Title: Debian playermodules Manual
Author: <insert document author here>
Abstract: This manual describes what playermodules is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/playermodules/playermodules.sgml.gz

Format: postscript
Files: /usr/share/doc/playermodules/playermodules.ps.gz

Format: text
Files: /usr/share/doc/playermodules/playermodules.text.gz

Format: HTML
Index: /usr/share/doc/playermodules/html/index.html
Files: /usr/share/doc/playermodules/html/*.html
